### ISSUE TITLE
consider move minimist to dev-dependencies

### ISSUE THREAD

**Issue by royriojas** [blakelapierre/promise-callback#1]
minimist is currently being installed as a dependency which I guess is not right since it is not used by the `promise-callback` module but during building.

**Comment by blakelapierre** [comment]
Good catch! Thanks!

Feel free to submit a pull request, or else I will update this soon. Probably by the end of the day.

**Comment by blakelapierre** [comment]
This has been fixed.

Thanks for the report. Much appreciated!
